### ISSUE TITLE
Any way to load from Compose Resource?

### ISSUE THREAD

**Issue by armond-avanes** [kkostov/gadulka#3]
I'm looking for an API to be able to load audio files bundled with app. Or at least to be able to pass in a ByteArray of content to play. Looking into the docs and the source code, the only option was to play an online resource.

**Comment by kkostov** [comment]
Hi @armond-avanes, you're correct that there is no dedicated API for resources. Would it be a solution to use the[Resources api](https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-resources.html) for raw files:

1. You place the audio file in the resources folder for raw files e.g. `composeResources\files\sample.mp3`

2. Get the resource URI and pass it to the library:

```kotlin
// val player = GadulkaPlayer()
val uri = Res.getUri("files/sample.mp3")
player.play(uri)
```

**Comment by kkostov** [comment]
I tested the approach above on Android, iOS and JVM and it seemed to work (not sure why, I think may be because of https://github.com/JetBrains/compose-multiplatform/pull/4965?), but perhaps it's not ideal for all situations.

You're definitely right that it makes sense to have a dedicated API using resources - it will make the interface of the library more accessible and easier to use.
